url: "https://delosreyesdonna.github.io"
baseurl: "/pages"

title: "Donna Marie Portfolio"
email: "your-email@domain.com"
description: "My personal portfolio website"

markdown: kramdown
permalink: pretty
